const Constants = {
  SETMAIL: "SETMAIL",
  MARKFAVORITE: "MARKFAVORITE",
  MARKREAD: "MARKREAD",
  SETCURRENT: "SETCURRENT",
  UNSETCURRENT: "UNSETCURRENT",
  SETFILTER: "SETFILTER",
};
export { Constants };
